<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Properties/LangFilesEditor.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
    <PackageReference Include="ModPlusAPI" Version="40.0.0" />
  </ItemGroup>

  <!--  todo: а должны ли они здесь все так страничками быть указаны?-->
  <ItemGroup>
    <Page Update="UI\Windows\MainWindow\MainWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="UI\Windows\MainWindow\NavBar.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="UI\Windows\MainWindow\SearchBar.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="UI\Windows\MainWindow\ToolBar.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="UI\Windows\MainWindow\WorkSpace\WorkSpace.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="UI\Windows\Dictionaries\TranslationEntriesGrid.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="UI\Windows\Dictionaries\TranslationEntriesGridResources.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="UI\Windows\Dictionaries\ItemView.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="UI\Windows\DialogWindows\Merger.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="UI\Windows\DialogWindows\ImportWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="UI\Windows\DialogWindows\ImportWindowWithCheckbox.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="UI\Windows\DialogWindows\MarkForDeletionWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="UI\Windows\MainWindow\WorkSpace\ModuleView.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModPlus.Analyzer" Version="3.0.0" ExcludeAssets="runtime" />
  </ItemGroup>
  
</Project>